#pragma checksum "..\..\bankReceipt.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2CBA25A8CC7872CE1729B38D75742C2A64DC2E67DB26E8651FE970E0BB4D96CB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using accounts;


namespace accounts {
    
    
    /// <summary>
    /// bankReceipt
    /// </summary>
    public partial class bankReceipt : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_brno;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_brnofind;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_find;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dtp_brdate;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_movefirst;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ImageBrush btn_login5;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_movenext;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ImageBrush btn_login2;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_movelast;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ImageBrush btn_login4;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_moveprevious;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ImageBrush btn_login1;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox info;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmb_cashaccount;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmb_draccount;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_chqNo;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_amount;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_bcharge;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_discamount;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_disc;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmb_status;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmb_typeofpayment;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_save;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Reset;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_print;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_help;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_update1;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_delete;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_report;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dtp_chdate;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_total;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_dr_report;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ImageBrush btn_login7;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_cr_report;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ImageBrush btn_login3;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_c;
        
        #line default
        #line hidden
        
        
        #line 143 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_p;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_narration;
        
        #line default
        #line hidden
        
        
        #line 147 "..\..\bankReceipt.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmb_jinv;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/accounts;component/bankreceipt.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\bankReceipt.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 8 "..\..\bankReceipt.xaml"
            ((accounts.bankReceipt)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.Window_KeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.txt_brno = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.txt_brnofind = ((System.Windows.Controls.TextBox)(target));
            
            #line 17 "..\..\bankReceipt.xaml"
            this.txt_brnofind.KeyDown += new System.Windows.Input.KeyEventHandler(this.txt_rnofind_KeyDown);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btn_find = ((System.Windows.Controls.Button)(target));
            
            #line 18 "..\..\bankReceipt.xaml"
            this.btn_find.Click += new System.Windows.RoutedEventHandler(this.btn_find_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.dtp_brdate = ((System.Windows.Controls.DatePicker)(target));
            
            #line 23 "..\..\bankReceipt.xaml"
            this.dtp_brdate.KeyUp += new System.Windows.Input.KeyEventHandler(this.dtp_brdate_KeyUp);
            
            #line default
            #line hidden
            return;
            case 6:
            this.btn_movefirst = ((System.Windows.Controls.Button)(target));
            
            #line 24 "..\..\bankReceipt.xaml"
            this.btn_movefirst.Click += new System.Windows.RoutedEventHandler(this.btn_movefirst_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.btn_login5 = ((System.Windows.Media.ImageBrush)(target));
            return;
            case 8:
            this.btn_movenext = ((System.Windows.Controls.Button)(target));
            
            #line 31 "..\..\bankReceipt.xaml"
            this.btn_movenext.Click += new System.Windows.RoutedEventHandler(this.btn_movenext_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.btn_login2 = ((System.Windows.Media.ImageBrush)(target));
            return;
            case 10:
            this.btn_movelast = ((System.Windows.Controls.Button)(target));
            
            #line 36 "..\..\bankReceipt.xaml"
            this.btn_movelast.Click += new System.Windows.RoutedEventHandler(this.btn_movelast_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.btn_login4 = ((System.Windows.Media.ImageBrush)(target));
            return;
            case 12:
            this.btn_moveprevious = ((System.Windows.Controls.Button)(target));
            
            #line 41 "..\..\bankReceipt.xaml"
            this.btn_moveprevious.Click += new System.Windows.RoutedEventHandler(this.btn_moveprevious_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.btn_login1 = ((System.Windows.Media.ImageBrush)(target));
            return;
            case 14:
            this.info = ((System.Windows.Controls.TextBox)(target));
            
            #line 48 "..\..\bankReceipt.xaml"
            this.info.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.info_TextChanged);
            
            #line default
            #line hidden
            return;
            case 15:
            this.cmb_cashaccount = ((System.Windows.Controls.ComboBox)(target));
            
            #line 49 "..\..\bankReceipt.xaml"
            this.cmb_cashaccount.GotFocus += new System.Windows.RoutedEventHandler(this.cmb_cashaccount_GotFocus);
            
            #line default
            #line hidden
            
            #line 49 "..\..\bankReceipt.xaml"
            this.cmb_cashaccount.KeyDown += new System.Windows.Input.KeyEventHandler(this.cmb_cashaccount_KeyDown);
            
            #line default
            #line hidden
            return;
            case 16:
            this.cmb_draccount = ((System.Windows.Controls.ComboBox)(target));
            
            #line 50 "..\..\bankReceipt.xaml"
            this.cmb_draccount.KeyDown += new System.Windows.Input.KeyEventHandler(this.cmb_draccount_KeyDown_1);
            
            #line default
            #line hidden
            return;
            case 17:
            this.txt_chqNo = ((System.Windows.Controls.TextBox)(target));
            
            #line 53 "..\..\bankReceipt.xaml"
            this.txt_chqNo.KeyDown += new System.Windows.Input.KeyEventHandler(this.txt_chqNo_KeyDown);
            
            #line default
            #line hidden
            return;
            case 18:
            this.txt_amount = ((System.Windows.Controls.TextBox)(target));
            
            #line 57 "..\..\bankReceipt.xaml"
            this.txt_amount.KeyDown += new System.Windows.Input.KeyEventHandler(this.txt_amount_KeyDown);
            
            #line default
            #line hidden
            return;
            case 19:
            this.txt_bcharge = ((System.Windows.Controls.TextBox)(target));
            
            #line 58 "..\..\bankReceipt.xaml"
            this.txt_bcharge.KeyDown += new System.Windows.Input.KeyEventHandler(this.txt_bcharge_KeyDown);
            
            #line default
            #line hidden
            return;
            case 20:
            this.txt_discamount = ((System.Windows.Controls.TextBox)(target));
            
            #line 59 "..\..\bankReceipt.xaml"
            this.txt_discamount.KeyDown += new System.Windows.Input.KeyEventHandler(this.txt_discamount_KeyDown);
            
            #line default
            #line hidden
            return;
            case 21:
            this.txt_disc = ((System.Windows.Controls.TextBox)(target));
            
            #line 60 "..\..\bankReceipt.xaml"
            this.txt_disc.KeyDown += new System.Windows.Input.KeyEventHandler(this.txt_disc_KeyDown);
            
            #line default
            #line hidden
            return;
            case 22:
            this.cmb_status = ((System.Windows.Controls.ComboBox)(target));
            
            #line 62 "..\..\bankReceipt.xaml"
            this.cmb_status.KeyDown += new System.Windows.Input.KeyEventHandler(this.cmb_status_KeyDown);
            
            #line default
            #line hidden
            return;
            case 23:
            this.cmb_typeofpayment = ((System.Windows.Controls.ComboBox)(target));
            
            #line 68 "..\..\bankReceipt.xaml"
            this.cmb_typeofpayment.KeyDown += new System.Windows.Input.KeyEventHandler(this.cmb_typeofpayment_KeyDown);
            
            #line default
            #line hidden
            return;
            case 24:
            this.btn_save = ((System.Windows.Controls.Button)(target));
            
            #line 75 "..\..\bankReceipt.xaml"
            this.btn_save.Click += new System.Windows.RoutedEventHandler(this.btn_save_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.btn_Reset = ((System.Windows.Controls.Button)(target));
            
            #line 80 "..\..\bankReceipt.xaml"
            this.btn_Reset.Click += new System.Windows.RoutedEventHandler(this.btn_Reset_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.btn_print = ((System.Windows.Controls.Button)(target));
            return;
            case 27:
            this.btn_help = ((System.Windows.Controls.Button)(target));
            return;
            case 28:
            this.btn_update1 = ((System.Windows.Controls.Button)(target));
            
            #line 95 "..\..\bankReceipt.xaml"
            this.btn_update1.Click += new System.Windows.RoutedEventHandler(this.btn_update1_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            this.btn_delete = ((System.Windows.Controls.Button)(target));
            
            #line 100 "..\..\bankReceipt.xaml"
            this.btn_delete.Click += new System.Windows.RoutedEventHandler(this.btn_delete_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.btn_report = ((System.Windows.Controls.Button)(target));
            
            #line 105 "..\..\bankReceipt.xaml"
            this.btn_report.Click += new System.Windows.RoutedEventHandler(this.btn_report_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            
            #line 110 "..\..\bankReceipt.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.dtp_chdate = ((System.Windows.Controls.DatePicker)(target));
            
            #line 115 "..\..\bankReceipt.xaml"
            this.dtp_chdate.GotFocus += new System.Windows.RoutedEventHandler(this.dtp_chdate_GotFocus);
            
            #line default
            #line hidden
            
            #line 115 "..\..\bankReceipt.xaml"
            this.dtp_chdate.KeyUp += new System.Windows.Input.KeyEventHandler(this.dtp_ChecqDate_KeyUp);
            
            #line default
            #line hidden
            
            #line 115 "..\..\bankReceipt.xaml"
            this.dtp_chdate.KeyDown += new System.Windows.Input.KeyEventHandler(this.dtp_chdate_KeyDown);
            
            #line default
            #line hidden
            return;
            case 33:
            this.txt_total = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 34:
            this.btn_dr_report = ((System.Windows.Controls.Button)(target));
            
            #line 118 "..\..\bankReceipt.xaml"
            this.btn_dr_report.Click += new System.Windows.RoutedEventHandler(this.btn_dr_report_Click);
            
            #line default
            #line hidden
            return;
            case 35:
            this.btn_login7 = ((System.Windows.Media.ImageBrush)(target));
            return;
            case 36:
            this.btn_cr_report = ((System.Windows.Controls.Button)(target));
            
            #line 123 "..\..\bankReceipt.xaml"
            this.btn_cr_report.Click += new System.Windows.RoutedEventHandler(this.btn_cr_report_Click);
            
            #line default
            #line hidden
            return;
            case 37:
            this.btn_login3 = ((System.Windows.Media.ImageBrush)(target));
            return;
            case 38:
            this.txt_c = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 39:
            this.txt_p = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 40:
            this.txt_narration = ((System.Windows.Controls.TextBox)(target));
            
            #line 145 "..\..\bankReceipt.xaml"
            this.txt_narration.KeyDown += new System.Windows.Input.KeyEventHandler(this.txt_narration_KeyDown);
            
            #line default
            #line hidden
            return;
            case 41:
            this.cmb_jinv = ((System.Windows.Controls.ComboBox)(target));
            
            #line 147 "..\..\bankReceipt.xaml"
            this.cmb_jinv.KeyDown += new System.Windows.Input.KeyEventHandler(this.cmb_jinv_KeyDown);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

